fruits=["apple","banana","oramge","mango","watermelon"]
print(fruits)
print(fruits[3])
print(fruits[1:4])
numbers=[1,2,3,4,5,6,7,8,9,10]
print(numbers)
print(numbers[::-1])
print(numbers[-6::-2])
print(numbers*3)